### ISSUE TITLE
Автоматический импорт файлов

### ISSUE THREAD

**Issue by EvgeniyChuprov** [fatfutor/hotels#10]
Сейчас все подтягивается директивами @import. Каждый раз при подключении-отключении блока нужно добавлять или убирать импорт руками. Нужно сделать функцию в точке входа (index.js), которая будет собирать все твои стилевые и js файлы. Тогда все  @import в файлах можно убрать.

**Comment by fatfutor** [comment]
![hotels -  Fhotels  -  sourceindex js - WebStorm 2016 1 1](https://user-images.githubusercontent.com/11800679/72911547-50766780-3d4b-11ea-98b6-7d6ddbfe7ef9.jpg)
c js все получилось, а вот scss проблемы. блоки не видят переменные и миксины

**Comment by EvgeniyChuprov** [comment]
Так у меня работает.
![Снимок экрана от 2020-01-23 14-42-21](https://user-images.githubusercontent.com/36810364/72981740-97696900-3dee-11ea-8f33-b4a90727fc68.png)
