### ISSUE TITLE
Подключаемые файлы

### ISSUE THREAD

**Issue by EvgeniyChuprov** [fatfutor/hotels#2]
Подключаемые файлы (картинки, шрифты и т.д.) - если в проекте нет индивидуальных соглашений, то они должны именоваться в стиле lower-case-hyphenated;

**Comment by EvgeniyChuprov** [comment]
Библиотеки и плагины подключаются через package.json
![Снимок экрана от 2020-01-22 12-35-52](https://user-images.githubusercontent.com/36810364/72882656-0625c400-3d14-11ea-954c-3ee5b9ba877d.png)

**Comment by fatfutor** [comment]
установил  через npm оба пакета
сделал настройку вебпак
![hotels -  Fhotels  -  configwebpack base conf js - WebStorm 2016 1 1](https://user-images.githubusercontent.com/11800679/72918240-63db0000-3d56-11ea-9a0f-bf3f1f3112f1.jpg)
в файле слайдера сделал так
![hotels -  Fhotels  -  sourceblocksrangerange js - WebStorm 2016 1 1](https://user-images.githubusercontent.com/11800679/72918363-95ec6200-3d56-11ea-8f7e-c15f81435aa6.jpg)
 выдает ошибку 
![Form Elements - Google Chrome](https://user-images.githubusercontent.com/11800679/72918432-b3b9c700-3d56-11ea-8a12-514141ee20d5.jpg)
