### ISSUE TITLE
Стили

### ISSUE THREAD

**Issue by EvgeniyChuprov** [fatfutor/hotels#3]
1 Размер указывать в относительных величинах.
2 В блоках по стандартам запрещено указывать внешние отступы, так же блоке не стоит применять padding для позиционирования блока.
3 Не применять стили к элементам, только к классам.

**Comment by EvgeniyChuprov** [comment]
Использовать вложенные правила во всех scss файлах.

**Comment by fatfutor** [comment]
> 1 Размер указывать в относительных величинах.
> 2 В блоках по стандартам запрещено указывать внешние отступы, так же блоке не стоит применять padding для позиционирования блока.
> 3 Не применять стили к элементам, только к классам.

> 1 это требование абсолютно ко всем размерам (min/max-height/width)?
> 2 внешние маргины нашел только margin: auto - это не допустимо?
> 3 http://joxi.ru/ZrJQBd6Cwgkw6A - это допустимо, других примеров не обнаружил

**Comment by fatfutor** [comment]
1 Размер указывать в относительных величинах. - с этим пунктом я встретил ряд сложностей
- border-radius когда элемент прямоугольный нужно задавать несколько правил
- декоративные элементы
![joxi_screenshot_1578912111540](https://user-images.githubusercontent.com/11800679/72249467-8197bf00-360a-11ea-994f-fb2c5362647c.png)
к примеру этот квадратик тоже должен быть в процентах
- есть ли исключения? нужно все-все переводить в % ?

**Comment by EvgeniyChuprov** [comment]
`Есть ли исключения? нужно все-все переводить в % ?`

Относительные величины - не только %. То же скругление квадрата можно в rem делать.

**Comment by EvgeniyChuprov** [comment]
Пиксели еще встречаются в проекте.
![Снимок экрана от 2020-01-20 14-19-08](https://user-images.githubusercontent.com/36810364/72722635-d948a400-3b8f-11ea-8826-4cd758037dd8.png)

**Comment by fatfutor** [comment]
думаю теперь все, искал через поиск в каждом файле стилей

**Comment by EvgeniyChuprov** [comment]
Убрать неиспользуемые стили.
![Снимок экрана от 2020-01-27 13-18-14](https://user-images.githubusercontent.com/36810364/73166759-89298e80-4107-11ea-98ec-59d4fc57665e.png)

Сейчас вложенные правила в scss где используются, где то нет.
лучше все классы писать так:
```
.block
  &__element
     &_modifier
```

**Comment by fatfutor** [comment]
> Убрать неиспользуемые стили.
> ![Снимок экрана от 2020-01-27 13-18-14](https://user-images.githubusercontent.com/36810364/73166759-89298e80-4107-11ea-98ec-59d4fc57665e.png)
> 
> Сейчас вложенные правила в scss где используются, где то нет.
> лучше все классы писать так:
> 
> ```
> .block
>   &__element
>      &_modifier
> ```
для того чтобы легче читать стили я использовал правило блок отдельно, элемент отдельно, а модификаторы и псевдоклассы вкладывал - это читабельнее
> .block
>   &__element
>      &_modifier
> ```
>.block
>   &_modifier
>
>.block__element
>   &:after
>   &_modifier

**Comment by EvgeniyChuprov** [comment]
Не могу утверждать, что это обязательно.
Общепринято что ли + удобнее для восприятия.
[БЭМ синтаксис](https://habr.com/ru/sandbox/76268/)
![Снимок экрана от 2020-01-27 14-22-37](https://user-images.githubusercontent.com/36810364/73170864-854e3a00-4110-11ea-9a3c-37e31e7f6ca5.png)

**Comment by fatfutor** [comment]
в рабочем проекте с участием других разработчиков я думаю нужно следовать одному стилю написания, но так как это учебный, оставлю как есть, если не будет возражения =)
