### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by EvgeniyChuprov** [fatfutor/hotels#4]
1. Переписать js на классы ES6.
2. Код должен соответствовать стандартам fsd и стайлгайду AirBnB, в том числе и по оформлению. Никаких var, ++ и так далее. 
3. Поставить ESlint и настроить его на правила AirBnB.

**Comment by EvgeniyChuprov** [comment]
Обращение к элементам
![Снимок экрана от 2019-12-25 14-51-28](https://user-images.githubusercontent.com/36810364/71444898-1606b400-2726-11ea-865c-8c36b6c02e6d.png)

**Comment by EvgeniyChuprov** [comment]
Конструктор должен быть максимально легковесным, сейчас же в некоторых классах почти весь код в конструкторе, в остальных вообще весь код в нем. 
+ нужно обозначать приватные методы знаком  `_`.

**Comment by EvgeniyChuprov** [comment]
1. Все export -ы должны быть внизу файла, а по сути, в данном проекте, вообще не нужны.
2. С конструкторами в классах проблемы так и остались.
Конструктор должен принимать параметры и содержать один два метода (образно говоря).
Условий в нем тоже быть не должно.
![Снимок экрана от 2020-01-29 13-05-57](https://user-images.githubusercontent.com/36810364/73347114-1dc2f680-4298-11ea-9fcf-7d7691ecbe03.png)
3. range.js вообще не классном описан.

**Comment by fatfutor** [comment]
range - это же библиотека, я его по документации подключил

**Comment by EvgeniyChuprov** [comment]
1. Осталось поправить конструктор в CheckboxList.js.
2. Нужно обращаться к элементам по классу, для этого и ставится префикс js- и пишем на классах, чтоб у каждого элемента был свой инстас.  
![Снимок экрана от 2020-01-30 14-29-18](https://user-images.githubusercontent.com/36810364/73445957-f0944800-436c-11ea-9d1f-7bd02177b7c4.png)

**Comment by fatfutor** [comment]
спасибо, поправлю

**Comment by EvgeniyChuprov** [comment]
`Это уже конец? =)`
Почти ) Проверка идет в два этапа, после меня будет еще один проверяющий.

`если не использовать id, то как быть когда несколько списков?`
Например "циклом" обойти все js-checkbox-list и для каждого создать свой экземпляр класса.

**Comment by fatfutor** [comment]
"Почти ) Проверка идет в два этапа, после меня будет еще один проверяющий." - жизнь - боль)

**Comment by EvgeniyChuprov** [comment]
Убрать все комментарии.
Про экспорты я уже писал.
