### ISSUE TITLE
БЭМ, компонентность

### ISSUE THREAD

**Issue by EvgeniyChuprov** [fatfutor/hotels#5]
Второй класс я так понимаю модификатор? Он в БЭМ обозначается не так.
![Снимок экрана от 2019-12-25 14-24-04](https://user-images.githubusercontent.com/36810364/71444439-43e9f980-2722-11ea-861c-9cf0dfdeabba.png)

Директория миксина, его файлы, его имя и  класс должны иметь одинаковое название. Тут получается 3 разных миксина-блока в одной директории. 
![Снимок экрана от 2019-12-25 14-27-36](https://user-images.githubusercontent.com/36810364/71444497-bbb82400-2722-11ea-8f54-5a991565d9ae.png)
Тут имя миксина вообще не объявлено + название файла и класс не совпадают.
![Снимок экрана от 2019-12-25 14-34-48](https://user-images.githubusercontent.com/36810364/71444620-c32bfd00-2723-11ea-90a4-e396083de596.png)
Поправить везде.

**Comment by EvgeniyChuprov** [comment]
Деструктуризировать полученные в миксин параметры.
Параметры передавать сверху от корня в виде объектов. Тут должен быть реализован компонентный подход подобный подходу, применяемому в реакте, но на миксинах.

**Comment by EvgeniyChuprov** [comment]
Нельзя объявлять в одном файле несколько миксинов.
![Снимок экрана от 2019-12-25 15-04-14](https://user-images.githubusercontent.com/36810364/71445111-f07aaa00-2727-11ea-9481-fb585d057bbf.png)

**Comment by fatfutor** [comment]
- "Второй класс я так понимаю модификатор? Он в БЭМ обозначается не так."
Ошибка в стиле написания, два тире, или слово width?
- в макете присутствуют страницы которые повторяются трижды, могу я верстать только одну?

**Comment by EvgeniyChuprov** [comment]
- [Обозначение модификаторов](https://ru.bem.info/methodology/quick-start/)
- Несколько вариантов страниц, для примера, как должны отображаться изменяемые элементы.
Можно делать 1.

**Comment by fatfutor** [comment]
Здесь нет замечаний?

**Comment by EvgeniyChuprov** [comment]
Пока не заметил, но не факт что не найду позже)

**Comment by EvgeniyChuprov** [comment]
Тут вероятно описка в названии класса .filter-dropdown__title
![Снимок экрана от 2020-01-22 12-32-14](https://user-images.githubusercontent.com/36810364/72882220-4a649480-3d13-11ea-8321-b4599aa3659a.png)
