### ISSUE TITLE
Различные правки

### ISSUE THREAD

**Issue by EvgeniyChuprov** [fatfutor/hotels#6]
Не использовать числа в названиях.
![Снимок экрана от 2019-12-25 14-46-18](https://user-images.githubusercontent.com/36810364/71444822-5ca7de80-2725-11ea-9e35-ffec0e35a087.png)

**Comment by EvgeniyChuprov** [comment]
Убрать весь закомментированный код и неиспользуемые элементы.

**Comment by EvgeniyChuprov** [comment]
Замечания во всех issue применять ко всему проекту, а не только в указанном месте.

**Comment by EvgeniyChuprov** [comment]
При запуске проекта нет возможности перейти на другую страницу или UI. Добавить ссылки на другие страницы, как вариант, чтоб первой открывалась страница содержащая ссылки на остальные станицы.

**Comment by EvgeniyChuprov** [comment]
В figma указана ширина страниц - width: 1440px. Сейчас они растягиваются на всю ширину экрана.

**Comment by fatfutor** [comment]
> В figma указана ширина страниц - width: 1440px. Сейчас они растягиваются на всю ширину экрана.

Нужно задать максимальную ширину 1440px?

**Comment by EvgeniyChuprov** [comment]
Да.

**Comment by EvgeniyChuprov** [comment]
Зачем префикс js- если в миксине нет js кода?
![Снимок экрана от 2020-01-20 13-40-46](https://user-images.githubusercontent.com/36810364/72720240-920be480-3b8a-11ea-9f24-9e866f033d46.png)

**Comment by EvgeniyChuprov** [comment]
Лучше вместо var использовать let или const
![Снимок экрана от 2020-01-20 13-46-50](https://user-images.githubusercontent.com/36810364/72720574-54f42200-3b8b-11ea-8d65-5b8ab0a68de1.png)

**Comment by fatfutor** [comment]
заменил все var через поиск

**Comment by EvgeniyChuprov** [comment]
Файл varables.pug вообще не нужен. Все параметры нужно передавать из корневого миксина. Миксин страницы который содержит внутри себя остальные миксины, в него передается объект содержащий все параметры для вложенных миксинов. Вложенные миксины  применяют параметры к себе и передают параметры в свои вложенные миксины и так далее.
Надеюсь понятно описал.

**Comment by EvgeniyChuprov** [comment]
Все include делать в начале файла
![Снимок экрана от 2020-01-21 11-42-42](https://user-images.githubusercontent.com/36810364/72788567-2c2f6380-3c43-11ea-8d0c-70d96e4f5424.png)

**Comment by EvgeniyChuprov** [comment]
В коммитах желательно писать о том какие изменения в нем происходят или что изменяется
![Снимок экрана от 2020-01-21 11-45-46](https://user-images.githubusercontent.com/36810364/72788818-9811cc00-3c43-11ea-9abc-cc56163c28b7.png)

**Comment by EvgeniyChuprov** [comment]
Именование должно быть осмысленным. Что значит? 
![Снимок экрана от 2020-01-22 12-40-56](https://user-images.githubusercontent.com/36810364/72883059-b1cf1400-3d14-11ea-8e18-829abf628370.png)

**Comment by EvgeniyChuprov** [comment]
Возможно не заметил, но не вижу где подключаются favicon?
