### ISSUE TITLE
Pixel perfect

### ISSUE THREAD

**Issue by EvgeniyChuprov** [fatfutor/hotels#9]
![Снимок экрана от 2020-01-20 14-40-00](https://user-images.githubusercontent.com/36810364/72724057-5a556a80-3b93-11ea-89c6-317417dfb82c.png)

**Comment by fatfutor** [comment]
![Form Elements - Google Chrome](https://user-images.githubusercontent.com/11800679/72730805-36018a00-3ba3-11ea-93e8-8d679422cbd5.jpg)
хром 1440px

**Comment by fatfutor** [comment]
расхождение только по чекбоксу

**Comment by EvgeniyChuprov** [comment]
![image](https://user-images.githubusercontent.com/36810364/73249492-0adff180-41c6-11ea-9d95-4227d70441c2.png)

**Comment by fatfutor** [comment]
![486ac3ac0c](https://user-images.githubusercontent.com/11800679/73257583-1555b780-41d5-11ea-979a-fd24212b1dab.jpg)

**Comment by fatfutor** [comment]
у нас видимо разные макеты
